### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by wangclin** [XinyiYS/Robust-and-Fair-Federated-Learning#1]
Hi, I met this issue when I download MNIST dataset: 
Downloading http://yann.lecun.com/exdb/mnist/https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz
Failed to download (trying next):
HTTP Error 404: Not Found

Downloading https://ossci-datasets.s3.amazonaws.com/mnist/https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz
Failed to download (trying next):
HTTP Error 404: Not Found

**Comment by wangclin** [comment]
I # resources(line 272) in Data_Prepper.py.  It s ok

**Comment by XinyiYS** [comment]
closing the issue. since it seems addressed.

The issue was due to a broken url for downloading the mnist dataset. Removing the MNIST.resources can fix it.
