### ISSUE TITLE
How to calculate Fairness results?

### ISSUE THREAD

**Issue by skyejy** [XinyiYS/Robust-and-Fair-Federated-Learning#5]

**Comment by skyejy** [comment]
Hello, your work is excellent~I read the paper and its codes carefully.
I really wonder how to get the results of Table 2 in paper.  And could you please also share the codes of q-FFL and CFFL?
![image](https://user-images.githubusercontent.com/26304541/177033004-5ce66394-f4f3-4512-8b94-f0d74a861ca9.png)

Looking forward to your reply. Thanks~

**Comment by XinyiYS** [comment]
Thanks for the interest in our work!

Do you mean what we use as the fairness metric, in which case the metric is the Pearson correlation coefficient between the standalone test accuracies (without collaboration) _and_ the test accuracies of each after collaboration. In both cases the test accuracies are obtained on a single hold-out test set. 

We use the original code for [q-FFL](https://github.com/litian96/fair_flearn) and our other repository for [CFFL](https://github.com/XinyiYS/CollaborativeFairFederatedLearning).

P.S. Our NeurIPS'21 paper [Gradient Driven Rewards to Guarantee Fairness in Collaborative Machine Learning](https://proceedings.neurips.cc/paper/2021/hash/8682cc30db9c025ecd3fee433f8ab54c-Abstract.html) with [code](https://github.com/XinyiYS/Gradient-Driven-Rewards-to-Guarantee-Fairness-in-Collaborative-Machine-Learning) has a more in-depth theoretical analysis on fairness for a similar implementation to this work.

**Comment by skyejy** [comment]
> Thanks for the interest in our work!
> 
> Do you mean what we use as the fairness metric, in which case the metric is the Pearson correlation coefficient between the standalone test accuracies (without collaboration) _and_ the test accuracies of each after collaboration. In both cases the test accuracies are obtained on a single hold-out test set.
> 
> We use the original code for [q-FFL](https://github.com/litian96/fair_flearn) and our other repository for [CFFL](https://github.com/XinyiYS/CollaborativeFairFederatedLearning).
> 
> P.S. Our NeurIPS'21 paper [Gradient Driven Rewards to Guarantee Fairness in Collaborative Machine Learning](https://proceedings.neurips.cc/paper/2021/hash/8682cc30db9c025ecd3fee433f8ab54c-Abstract.html) with [code](https://github.com/XinyiYS/Gradient-Driven-Rewards-to-Guarantee-Fairness-in-Collaborative-Machine-Learning) has a more in-depth theoretical analysis on fairness for a similar implementation to this work.

Thanks a lot, I will try~
And congratulations on your new achievement!
