### ISSUE TITLE
Confusion regarding the standalone model and average accuracy

### ISSUE THREAD

**Issue by Nawrin14** [XinyiYS/Robust-and-Fair-Federated-Learning#7]
Hi, 

I am trying to reproduce table 1 and 2 of the paper.  However, I have two questions - 

1. Can you explain how to find the standalone model accuracy to measure fairness? According to the paper, "Standalone performance is the test accuracy of a model trained only on the participant's local data". As this model is not affected by federated training, the model is fixed. Again, each participant's local data is also fixed. So, shouldn't this model accuracy be the same in each round? 

2. How did you find the average test accuracy in table 1? Is it the average of N participants or the average of all rounds?

Thanks.

**Comment by XinyiYS** [comment]
Thanks for the questions. See below
> 1. Can you explain how to find the standalone model accuracy to measure fairness? According to the paper, "Standalone performance is the test accuracy of a model trained only on the participant's local data". As this model is not affected by federated training, the model is fixed. Again, each participant's local data is also fixed. So, shouldn't this model accuracy be the same in each round?

You are correct that each standalone model is not affected by federated training. However, each standalone model undergoes an iterative training by each participant. The round in FL corresponds to the iteration in local standalone model training. In other words, during the local training (e.g., 100 iterations) the model performance changes while after the training is complete, the model performance of these participants are different.

> 2. How did you find the average test accuracy in table 1? Is it the average of N participants or the average of all rounds?

It is the average test accuracy _after_ the entire training (standalone or FL) is complete over all the participants. Put differently, after training, the test accuracy of each model evaluated and an average is taken over them.

**Comment by Nawrin14** [comment]
Thanks for your response.
